chart = { package = "yew-chart", version = "0.6" }
plotly = { package = "yew-plotly", version = "0.7" }
[package]
name = "applyforge"
version = "0.1.0"
edition = "2021"
description = "Template for starting a Yew project using Trunk"
readme = "README.md"
repository = "https://github.com/yewstack/yew-trunk-minimal-template"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]


[dependencies]
yew = { version="0.21", features=["csr"] }
web-sys = { version = "0.3", features = ["HtmlInputElement", "HtmlSelectElement"] }
js-sys = "0.3"
gloo-net = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen-futures = "0.4.50"
gloo = "0.11.0"
gloo-storage = "0.3"
gloo-utils = "0.2.0"
uuid = { version = "1.8", features = ["v4", "serde", "js"] } # Added js feature for WASM RNG
plotters = { version = "0.3", default-features = false, features = ["svg_backend"] }
