FROM rust:1.86-slim-bookworm AS builder
WORKDIR /app
COPY backend /app/backend
WORKDIR /app/backend
RUN rm -f /app/backend/target && mkdir -p /app/backend/target
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app/backend
RUN mkdir -p /app/backend
COPY --from=builder /app/backend/target/release/backend /app/backend/backend
CMD ["/app/backend/backend"]
