FROM rust:1.86-slim-bookworm AS builder
WORKDIR /app
RUN cargo install trunk
RUN rustup target add wasm32-unknown-unknown
COPY frontend /app/frontend
WORKDIR /app/frontend
RUN trunk build --release

FROM nginx:alpine
COPY --from=builder /app/frontend/dist /usr/share/nginx/html
